version: 0.4.0
slug: upmpdcli
name: upmpdcli
description: upmpdcli is a UPnP Media Renderer front-end for MPD, the Music Player Daemon. It supports UPnP gapless track transitions and the OpenHome ohMedia services (including a Radio service to listen to Internet streams)
url: https://github.com/mavrikkk/hassio-addons/tree/main/upmpdcli
arch:
  - amd64
  - armhf
  - armv7
  - i386
audio: true
init: false
host_network: true
options: 
  friendlyname: "HA UPnP player"
  ohproductroom: "HA UPnP player"
schema: 
  friendlyname: "str"
  ohproductroom: "str"
ports:
  49152/tcp: 49152
  1900/udp: 1900
ports_description": 
  49152/tcp: "upnp port"
  1900/udp: "upnp port"
stage: stable
startup: services
